os:
- linux
- osx
language: node_js
node_js:
- '10'
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run test -- carousel --watch false
before_deploy:
- npm run build
- cd dist/carousel
deploy:
  provider: npm
  email: gabriel20053@gmail.com
  cleanup: true
  api_key:
    secure: i/6mvoabKER/xJtk781C2au0AsZtoAmZPk3A+lFvoP8cbTeCrmdgePPtMQvtfKBgfGmDvyQuakuPQW/W4WArJtf1WupAXYx1rFE8hJ5XVJYuYecZV+9lp/LwSi3KbsytguIJVCtK46ezO+9LxuJNNF5RLv22pF/sBs2WKk4bnAjWC3DWB6ZsisQ2+cuA8xJIAI0zMKOxrMOpew/uZjPIyiU09gb7STcz+/J3muUTCDJgz4xJj0bfRWWF3Sl/4OPXvHtVa7UsuIv9U5iMdYylkxtVXlbJoF7U8pbt8GOkVcBLs0qV+Jl5iB9J532bXdl1S2v1OWDl7o5qGn7MsbuU6iPAPi/aChGNF218x/aNYFQbYodAA59p9iBWj0vMbX13xYNwstmkMufVQbZhwZ/KG63J8u2QBKIxqGbK+yFWtEGCH3Xo9M4qpy9X8fTpSmhh/t5umo+s43HqsuYICbhHrboRSTI3/eV7D+HVCiiYi6/S9jukDA2UdZIMNUp5Ht8Ys1Z3MsKHn/JEIg0z9gsiHGUwsOscHlpqkz0DjDoDVYXuk0vB8bE4Q4g4zSGw8358u83xFvGKdd8Tfxbr/E1zQrd8M16XYC66deTe5s7apH3b2TNPLcwFxZevmuKiXVqU7J2847NgGGhObqGT+86ANCGkT1HrLLgiT8RyA7IwjYI=
  on:
    tags: true
    repo: gabrielbusarello/material2-carousel
